version: '3'

services: 
  nginx:
    build: 
      dockerfile: ./nginx.dockerfile
      context: .
    image: vitorceron/nginx
    container_name: nginx-nodejs
    ports: 
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"

  node1: 
    build: 
      dockerfile: ./nodes.dockerfile
      context: .
    image: vitorceron/nodes
    container_name: node1
    ports: 
      - "3000"
    networks: 
      - production-network
    volumes: 
      - .:/usr/app

  node2: 
    build: 
      dockerfile: ./nodes.dockerfile
      context: .
    image: vitorceron/nodes
    container_name: node2
    ports: 
      - "3000"
    networks: 
      - production-network
    volumes: 
      - .:/usr/app

  node3: 
    build: 
      dockerfile: ./nodes.dockerfile
      context: .
    image: vitorceron/nodes
    container_name: node3
    ports: 
      - "3000"
    networks: 
      - production-network
    volumes: 
      - .:/usr/app

networks: 
    production-network:
        driver: bridge